### ISSUE TITLE
Core: Unable to join Earth due to ProtocolLib error

### ISSUE THREAD

**Issue by vyketype** [PixliesEarth/PixliesCoreV2#44]
I am unable to join Earth because of the following error from ProtocolLib which persists when a player joins:

> [16:57:37 ERROR]: [PixliesCore] Unhandled exception occurred in onPacketSending(PacketEvent) for PixliesCore
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:245) ~[ProtocolLib.jar:?]
        at net.pixlies.core.packets.impl.player.TabListPacketAdapter.onPacketSending(TabListPacketAdapter.java:32) ~[PixliesCore.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2234) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:528) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.pixlies.core.handlers.impl.TabListHandler.updateDisplayNames(TabListHandler.java:77) ~[PixliesCore.jar:?]
        at net.pixlies.core.runnables.impl.TabListRunnable.run(TabListRunnable.java:27) ~[PixliesCore.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:57:37 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@15289364[
    a=[UPDATE_DISPLAY_NAME]
    b=[b[profileId=d192b8bf-d8bc-4992-a3bf-b0544ad0fce4, profile=com.mojang.authlib.GameProfile@3a9a5390[id=d192b8bf-d8bc-4992-a3bf-b0544ad0fce4,name=vyketype,properties={textures=[com.mojang.authlib.properties.Property@3ef49915]},legacy=false], listed=true, latency=0, gameMode=SURVIVAL, displayName=null, chatSession=null]]
  ]

**Comment by dynmie** [comment]
Fixed
